services:
  java-scraper:
    build: ./producer-java
    image: bansikah/java-scraper:1.0
    volumes:
      - ./shared-data:/app/shared-data
    command: sh -c "java -jar app.jar"

  python-consumer:
    build: ./consumer-python
    image: bansikah/python-consumer:1.0
    volumes:
      - ./shared-data:/app/shared-data
    command: sh -c "python consumer.py"